export const APPLICATION_ENDPOINT = 'application'
export const AUTH_ENDPOINT = 'auth'
export const CONSTITUENCY_ENDPOINT = 'constituency'
export const ELECTIONS_ENDPOINT = 'elections'
export const USER_ENDPOINT = 'user'
export const VOTE_ENDPOINT = 'vote'
